# Generated by Django 5.1.1 on 2024-09-16 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='G6PDAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_history', models.BooleanField()),
                ('close_relatives', models.BooleanField()),
                ('weakness_fatigue', models.BooleanField()),
                ('jaundice', models.BooleanField()),
                ('dark_urine', models.BooleanField()),
                ('eaten_fava_beans', models.BooleanField()),
                ('medication_triggers', models.JSONField()),
                ('ethnic_risk', models.BooleanField()),
                ('lived_in_malaria_region', models.BooleanField()),
                ('jaundiced_after_birth', models.BooleanField(blank=True, null=True)),
                ('required_phototherapy', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
