# Generated by Django 5.1.1 on 2024-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_productimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
